2015-03-20T22:19:24.283149+00:00 app[web.1]:     self.manage_workers()
2015-03-20T22:19:24.283442+00:00 app[web.1]:     self.reap_workers()
2015-03-20T22:19:24.258977+00:00 app[web.1]: Traceback (most recent call last):
2015-03-20T22:19:24.259019+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-03-20T22:19:24.258990+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-03-20T22:19:24.259007+00:00 app[web.1]: ImportError: Import by filename is not supported.
2015-03-20T22:19:24.245375+00:00 app[web.1]: [2015-03-20 22:19:24 +0000] [6] [INFO] Starting gunicorn 19.3.0
2015-03-20T22:19:24.258985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-03-20T22:19:24.259008+00:00 app[web.1]: Traceback (most recent call last):
2015-03-20T22:19:24.259020+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-03-20T22:19:24.259024+00:00 app[web.1]: ImportError: Import by filename is not supported.
2015-03-20T22:19:24.259041+00:00 app[web.1]: [2015-03-20 22:19:24 +0000] [11] [INFO] Worker exiting (pid: 11)
2015-03-20T22:19:24.258981+00:00 app[web.1]:     worker.init_process()
2015-03-20T22:19:24.258986+00:00 app[web.1]:     self.callable = self.load()
2015-03-20T22:19:24.259011+00:00 app[web.1]:     worker.init_process()
2015-03-20T22:19:24.259013+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-03-20T22:19:24.258982+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2015-03-20T22:19:24.259009+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2015-03-20T22:19:24.259017+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-03-20T22:19:24.258988+00:00 app[web.1]:     return self.load_wsgiapp()
2015-03-20T22:19:24.259015+00:00 app[web.1]:     self.callable = self.load()
2015-03-20T22:19:24.258987+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-03-20T22:19:24.259006+00:00 app[web.1]:     __import__(module)
2015-03-20T22:19:24.259014+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-03-20T22:19:24.258991+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-03-20T22:19:24.259012+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2015-03-20T22:19:24.259023+00:00 app[web.1]:     __import__(module)
2015-03-20T22:19:24.259021+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-03-20T22:19:24.258979+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2015-03-20T22:19:24.258983+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-03-20T22:19:24.258973+00:00 app[web.1]: [2015-03-20 22:19:24 +0000] [11] [ERROR] Exception in worker process:
2015-03-20T22:19:24.259018+00:00 app[web.1]:     return self.load_wsgiapp()
2015-03-20T22:19:24.259005+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-03-20T22:19:24.282707+00:00 app[web.1]: Traceback (most recent call last):
2015-03-20T22:19:25.062614+00:00 heroku[web.1]: Process exited with status 1
2015-03-20T22:19:25.099707+00:00 heroku[web.1]: State changed from starting to crashed
2015-03-21T00:34:58.679676+00:00 heroku[web.1]: State changed from crashed to starting
2015-03-21T00:35:04.407803+00:00 heroku[web.1]: Starting process with command `python cf_project/manage.py collectstatic --noinput; gunicorn cf_project/cf_project.wsgi -b 127.0.0.1:8000 --log-file -`
2015-03-21T00:35:06.815611+00:00 app[web.1]: 0 static files copied to '/app/staticfiles', 75 unmodified.
2015-03-21T00:35:06.815592+00:00 app[web.1]: 
2015-03-21T00:35:07.405686+00:00 app[web.1]: [2015-03-21 00:35:07 +0000] [6] [INFO] Listening at: http://127.0.0.1:8000 (6)
2015-03-21T00:35:07.405781+00:00 app[web.1]: [2015-03-21 00:35:07 +0000] [6] [INFO] Using worker: sync
2015-03-21T00:35:07.422480+00:00 app[web.1]: [2015-03-21 00:35:07 +0000] [11] [INFO] Booting worker with pid: 11
2015-03-21T00:35:07.467412+00:00 app[web.1]: Traceback (most recent call last):
2015-03-21T00:35:07.467417+00:00 app[web.1]:   File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
2015-03-21T00:35:07.467549+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
2015-03-21T00:35:07.467455+00:00 app[web.1]:     sys.exit(run())
2015-03-21T00:35:07.467608+00:00 app[web.1]:     super(Application, self).run()
2015-03-21T00:35:07.467483+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
2015-03-21T00:35:07.467528+00:00 app[web.1]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2015-03-21T00:35:07.467631+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
2015-03-21T00:35:07.467689+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 174, in run
2015-03-21T00:35:07.467851+00:00 app[web.1]:     self.spawn_workers()
2015-03-21T00:35:07.467663+00:00 app[web.1]:     Arbiter(self).run()
2015-03-21T00:35:07.467973+00:00 app[web.1]:     time.sleep(0.1 * random.random())
2015-03-21T00:35:07.467884+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 541, in spawn_workers
2015-03-21T00:35:07.467773+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
2015-03-21T00:35:07.468197+00:00 app[web.1]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2015-03-21T00:35:07.467740+00:00 app[web.1]:     self.manage_workers()
2015-03-21T00:35:07.467994+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
2015-03-21T00:35:07.468309+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2015-03-21T00:35:07.468085+00:00 app[web.1]:     self.reap_workers()
2015-03-21T00:35:07.468118+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
2015-03-21T00:35:07.426515+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-03-21T00:35:07.426492+00:00 app[web.1]: [2015-03-21 00:35:07 +0000] [11] [ERROR] Exception in worker process:
2015-03-21T00:35:07.404919+00:00 app[web.1]: [2015-03-21 00:35:07 +0000] [6] [INFO] Starting gunicorn 19.3.0
2015-03-21T00:35:07.426497+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2015-03-21T00:35:07.426509+00:00 app[web.1]:     worker.init_process()
2015-03-21T00:35:07.426495+00:00 app[web.1]: Traceback (most recent call last):
2015-03-21T00:35:07.426511+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2015-03-21T00:35:07.426518+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-03-21T00:35:07.426513+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-03-21T00:35:07.426557+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-03-21T00:35:07.426562+00:00 app[web.1]:     __import__(module)
2015-03-21T00:35:07.426529+00:00 app[web.1]: Traceback (most recent call last):
2015-03-21T00:35:07.426522+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-03-21T00:35:07.426521+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-03-21T00:35:07.426539+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-03-21T00:35:07.426559+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-03-21T00:35:07.436090+00:00 app[web.1]: [2015-03-21 00:35:07 +0000] [11] [INFO] Worker exiting (pid: 11)
2015-03-21T00:35:07.426525+00:00 app[web.1]:     __import__(module)
2015-03-21T00:35:07.426533+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2015-03-21T00:35:07.426516+00:00 app[web.1]:     self.callable = self.load()
2015-03-21T00:35:07.426519+00:00 app[web.1]:     return self.load_wsgiapp()
2015-03-21T00:35:07.426530+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2015-03-21T00:35:07.426536+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-03-21T00:35:07.426563+00:00 app[web.1]: ImportError: Import by filename is not supported.
2015-03-21T00:35:07.426540+00:00 app[web.1]:     return self.load_wsgiapp()
2015-03-21T00:35:07.426560+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-03-21T00:35:07.426527+00:00 app[web.1]: ImportError: Import by filename is not supported.
2015-03-21T00:35:07.426537+00:00 app[web.1]:     self.callable = self.load()
2015-03-21T00:35:07.426524+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-03-21T00:35:07.426532+00:00 app[web.1]:     worker.init_process()
2015-03-21T00:35:07.426534+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-03-21T00:35:08.371562+00:00 heroku[web.1]: State changed from starting to crashed
2015-03-21T00:35:08.348338+00:00 heroku[web.1]: Process exited with status 1
2015-03-21T02:35:36.398853+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=tlake-codefellows-django.herokuapp.com request_id=688b5868-0fdc-4cf9-af6e-60d8892c04e1 fwd="50.135.106.132" dyno= connect= service= status=503 bytes=
2015-03-21T02:35:37.143693+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=tlake-codefellows-django.herokuapp.com request_id=268736ca-9b0f-43cf-90e0-d22a4f19591e fwd="50.135.106.132" dyno= connect= service= status=503 bytes=
2015-03-21T02:37:14.537781+00:00 heroku[api]: Scale to web=1 by tanner.lake@gmail.com
2015-03-21T02:42:21.038254+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=tlake-codefellows-django.herokuapp.com request_id=195bc357-7546-4490-a0c6-b3455962e1ef fwd="50.135.106.132" dyno= connect= service= status=503 bytes=
2015-03-21T02:42:22.288818+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=tlake-codefellows-django.herokuapp.com request_id=79ec4f65-185b-464b-92eb-8e2b447b8136 fwd="50.135.106.132" dyno= connect= service= status=503 bytes=
